# Generated by Django 5.2.7 on 2025-11-11 10:44

import django.db.models.deletion
import django.utils.timezone
import students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('name', models.CharField(help_text="Student's full name", max_length=200, validators=[students.validators.StudentValidator.validate_name])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, help_text='Date of birth (student must be 3-25 years old)', null=True, validators=[students.validators.StudentValidator.validate_date_of_birth])),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number (11 digits starting with 03)', max_length=20, null=True, validators=[students.validators.StudentValidator.validate_phone_number])),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_cnic', models.CharField(blank=True, help_text="Father's CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic])),
                ('father_contact', models.CharField(blank=True, help_text="Father's contact number (11 digits starting with 03)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_phone_number])),
                ('father_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_cnic', models.CharField(blank=True, help_text="Guardian's CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic])),
                ('guardian_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_cnic', models.CharField(blank=True, help_text="Mother's CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic])),
                ('mother_status', models.CharField(blank=True, choices=[('widowed', 'Widowed'), ('divorced', 'Divorced'), ('married', 'Married')], max_length=20, null=True)),
                ('mother_contact', models.CharField(blank=True, help_text="Mother's contact number (11 digits starting with 03)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_phone_number])),
                ('mother_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('zakat_status', models.CharField(blank=True, choices=[('applicable', 'Applicable'), ('not_applicable', 'Not Applicable')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Complete address (10-500 characters)', null=True, validators=[students.validators.StudentValidator.validate_address])),
                ('family_income', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly family income in PKR', max_digits=10, null=True, validators=[students.validators.StudentValidator.validate_positive_number])),
                ('house_owned', models.BooleanField(default=False)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent amount in PKR', max_digits=10, null=True, validators=[students.validators.StudentValidator.validate_positive_number])),
                ('terminated_on', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('current_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('last_class_passed', models.CharField(blank=True, max_length=50, null=True)),
                ('last_school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_class_result', models.CharField(blank=True, max_length=200, null=True)),
                ('old_gr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('from_year', models.IntegerField(blank=True, help_text='From year (2000-2030)', null=True, validators=[students.validators.StudentValidator.validate_year])),
                ('to_year', models.IntegerField(blank=True, help_text='To year (2000-2030)', null=True, validators=[students.validators.StudentValidator.validate_year])),
                ('transfer_reason', models.TextField(blank=True, null=True)),
                ('siblings_count', models.PositiveIntegerField(blank=True, help_text='Number of siblings (positive integer)', null=True)),
                ('father_status', models.CharField(blank=True, choices=[('alive', 'Alive'), ('dead', 'Dead')], max_length=20, null=True)),
                ('sibling_in_alkhair', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('gr_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('student_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('enrollment_year', models.IntegerField(blank=True, help_text='Year of enrollment (2000-2030)', null=True, validators=[students.validators.StudentValidator.validate_year])),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], help_text="Student's shift", max_length=20, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.campus')),
                ('classroom', models.ForeignKey(blank=True, help_text='Classroom where student is enrolled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.classroom')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
