# Generated by Django 5.2.7 on 2025-11-11 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behaviour', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybehaviourrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_behaviour_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentbehaviourrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='studenteventparticipation',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='behaviour.studentbehaviourrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybehaviourrecord',
            unique_together={('student', 'month')},
        ),
    ]
