# Generated by Django 5.2.7 on 2025-12-02 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0002_initial'),
        ('teachers', '0003_teacher_deleted_at_teacher_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject name (e.g., Mathematics, English)', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Auto-generated subject code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Subject description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this subject currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(help_text='Campus this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='campus.campus')),
                ('level', models.ForeignKey(blank=True, help_text='Level this subject is for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='classes.level')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
                'unique_together': {('name', 'campus', 'level')},
            },
        ),
        migrations.CreateModel(
            name='TimeTablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(help_text='Period start time')),
                ('end_time', models.TimeField(help_text='Period end time')),
                ('is_break', models.BooleanField(default=False, help_text='Is this a break period?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Classroom for this period', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_periods', to='classes.classroom')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_periods', to='timetable.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher assigned to this period', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_periods', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Time Table Period',
                'verbose_name_plural': 'Time Table Periods',
                'ordering': ['day', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'day', 'start_time'), name='unique_classroom_period'), models.UniqueConstraint(fields=('teacher', 'day', 'start_time'), name='unique_teacher_period')],
            },
        ),
    ]
