# Generated by Django 5.2.7 on 2025-12-02 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('teachers', '0003_teacher_deleted_at_teacher_is_deleted'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(help_text='Period start time')),
                ('end_time', models.TimeField(help_text='Period end time')),
                ('is_break', models.BooleanField(default=False, help_text='Is this a break period?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Classroom for this period', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetable_periods', to='classes.classroom')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_periods', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='class_periods', to='timetable.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher assigned to this period', on_delete=django.db.models.deletion.CASCADE, related_name='class_teaching_periods', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Class Time Table',
                'verbose_name_plural': 'Class Time Tables',
                'ordering': ['classroom', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(help_text='Period start time')),
                ('end_time', models.TimeField(help_text='Period end time')),
                ('is_break', models.BooleanField(default=False, help_text='Is this a break period?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Classroom where teaching', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_teaching_periods', to='classes.classroom')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_periods', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_periods', to='timetable.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher for this period', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetable_periods', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Time Table',
                'verbose_name_plural': 'Teacher Time Tables',
                'ordering': ['teacher', 'day', 'start_time'],
            },
        ),
        migrations.DeleteModel(
            name='TimeTablePeriod',
        ),
        migrations.AddConstraint(
            model_name='classtimetable',
            constraint=models.UniqueConstraint(fields=('classroom', 'day', 'start_time'), name='unique_class_period'),
        ),
        migrations.AddConstraint(
            model_name='teachertimetable',
            constraint=models.UniqueConstraint(fields=('teacher', 'day', 'start_time'), name='unique_teacher_period'),
        ),
    ]
