# Generated by Django 5.2.7 on 2025-12-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('timetable', '0002_classtimetable_teachertimetable_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'campus')},
        ),
    ]
