# Generated by Django 5.2.7 on 2025-12-04 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('timetable', '0003_alter_subject_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('name', models.CharField(help_text='Period name (e.g., Period 1, Break)', max_length=50)),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('is_break', models.BooleanField(default=False, help_text='Is this a break?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(help_text='Campus this timing belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shift_timings', to='campus.campus')),
            ],
            options={
                'verbose_name': 'Shift Timing',
                'verbose_name_plural': 'Shift Timings',
                'ordering': ['campus', 'shift', 'order', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('campus', 'shift', 'name'), name='unique_shift_period_name')],
            },
        ),
    ]
