# Generated by Django 5.2.7 on 2025-12-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('timetable', '0005_shifttiming_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttiming',
            options={'ordering': ['campus', 'shift', 'timetable_type', 'order', 'start_time'], 'verbose_name': 'Shift Timing', 'verbose_name_plural': 'Shift Timings'},
        ),
        migrations.RemoveConstraint(
            model_name='shifttiming',
            name='unique_shift_period_name',
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='timetable_type',
            field=models.CharField(choices=[('class', 'Class Timetable'), ('teacher', 'Teacher Timetable')], default='class', help_text='Type of timetable (class or teacher)', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='shifttiming',
            constraint=models.UniqueConstraint(fields=('campus', 'shift', 'timetable_type', 'name'), name='unique_shift_period_name'),
        ),
    ]
