# Generated by Django 5.2.7 on 2025-11-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principals', '0003_principal_deleted_at_principal_is_deleted'),
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcomplaint',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='approved_by',
            field=models.CharField(blank=True, help_text='coordinator or principal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='forwarded_to_principal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='forwarding_note',
            field=models.TextField(blank=True, help_text="Coordinator's note when forwarding to principal", null=True),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_requests', to='principals.principal'),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='requires_principal_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='teacher_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='teacher_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='teacher_satisfaction_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestcomplaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('pending_principal', 'Pending Principal Approval'), ('approved', 'Approved'), ('pending_confirmation', 'Pending Teacher Confirmation'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='submitted', max_length=25),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='new_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('pending_principal', 'Pending Principal Approval'), ('approved', 'Approved'), ('pending_confirmation', 'Pending Teacher Confirmation'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('pending_principal', 'Pending Principal Approval'), ('approved', 'Approved'), ('pending_confirmation', 'Pending Teacher Confirmation'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
