# Generated by Django 5.2.7 on 2025-11-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='holiday',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='holidays', to='classes.grade'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='holiday_set', to='classes.level'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='classes.level'),
        ),
    ]
