# Generated by Django 5.2.7 on 2025-11-20 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0002_initial'),
        ('coordinator', '0001_initial'),
        ('students', '0002_student_is_active'),
        ('teachers', '0002_initial'),
        ('transfers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='transfer_category',
            field=models.CharField(blank=True, help_text='Optional category for this transfer (e.g. campus, shift_same_class).', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ClassTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_section', models.CharField(blank=True, max_length=10, null=True)),
                ('to_section', models.CharField(blank=True, max_length=10, null=True)),
                ('from_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('to_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField(help_text='Effective date requested for this change.')),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_reviewed', to='coordinator.coordinator')),
                ('from_classroom', models.ForeignKey(blank=True, help_text='Original classroom for this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_from', to='classes.classroom')),
                ('initiated_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_initiated', to='teachers.teacher')),
                ('principal', models.ForeignKey(blank=True, help_text='Optional final approver for class changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_transfers', to='students.student')),
                ('to_classroom', models.ForeignKey(blank=True, help_text='Destination classroom after transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_to', to='classes.classroom')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='transfers_c_status_41c284_idx'), models.Index(fields=['student'], name='transfers_c_student_8964f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShiftTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('to_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('status', models.CharField(choices=[('pending_own_coord', 'Pending Own Coordinator'), ('pending_other_coord', 'Pending Other Coordinator'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending_own_coord', max_length=40)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField(help_text='Effective date requested for this shift change.')),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_transfers', to='campus.campus')),
                ('from_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_from', to='classes.classroom')),
                ('from_shift_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_from_shift', to='coordinator.coordinator')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('requesting_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_initiated', to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_transfers', to='students.student')),
                ('to_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_to', to='classes.classroom')),
                ('to_shift_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_to_shift', to='coordinator.coordinator')),
                ('transfer_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfer', to='transfers.transferrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='transfers_s_status_c5d848_idx'), models.Index(fields=['student'], name='transfers_s_student_105125_idx'), models.Index(fields=['campus'], name='transfers_s_campus__a1e70c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransferApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('class', 'Class Transfer'), ('shift', 'Shift Transfer'), ('campus', 'Campus Transfer')], max_length=20)),
                ('transfer_id', models.PositiveIntegerField(help_text='Primary key of the underlying transfer object (ClassTransfer, ShiftTransfer, or TransferRequest).')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('coordinator_from', 'From Shift/Level Coordinator'), ('coordinator_to', 'To Shift/Level Coordinator'), ('principal', 'Principal')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('step_order', models.PositiveIntegerField(default=1, help_text='Logical order of this step within the workflow.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['transfer_type', 'transfer_id', 'step_order', '-created_at'],
                'indexes': [models.Index(fields=['transfer_type', 'transfer_id'], name='transfers_t_transfe_91ca59_idx'), models.Index(fields=['role'], name='transfers_t_role_2daa50_idx'), models.Index(fields=['status'], name='transfers_t_status_665509_idx')],
            },
        ),
    ]
