# Generated by Django 5.2.7 on 2025-11-24 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0002_initial'),
        ('coordinator', '0001_initial'),
        ('students', '0002_student_is_active'),
        ('teachers', '0002_initial'),
        ('transfers', '0003_transferrequest_transfer_category_classtransfer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSkipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('to_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('from_section', models.CharField(blank=True, max_length=10, null=True)),
                ('to_section', models.CharField(blank=True, max_length=10, null=True)),
                ('from_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('to_shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], help_text='Optional: destination shift (if different from current shift).', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending_own_coord', 'Pending Own Coordinator'), ('pending_other_coord', 'Pending Other Coordinator'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending_own_coord', max_length=40)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField(help_text='Effective date requested for this grade skip.')),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_skip_transfers', to='campus.campus')),
                ('from_classroom', models.ForeignKey(blank=True, help_text='Original classroom for this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_from', to='classes.classroom')),
                ('from_grade', models.ForeignKey(blank=True, help_text='Original grade for this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_from', to='classes.grade')),
                ('from_grade_coordinator', models.ForeignKey(blank=True, help_text="Coordinator for the student's current grade/level.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_from_grade', to='coordinator.coordinator')),
                ('initiated_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_initiated', to='teachers.teacher')),
                ('principal', models.ForeignKey(blank=True, help_text='Optional final approver for grade skip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_skip_transfers', to='students.student')),
                ('to_classroom', models.ForeignKey(blank=True, help_text='Destination classroom after grade skip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_to', to='classes.classroom')),
                ('to_grade', models.ForeignKey(blank=True, help_text='Destination grade after skip (must be exactly 1 grade ahead, e.g., Grade 1 → Grade 3).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_to', to='classes.grade')),
                ('to_grade_coordinator', models.ForeignKey(blank=True, help_text='Coordinator for the target grade/level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_to_grade', to='coordinator.coordinator')),
                ('transfer_request', models.OneToOneField(blank=True, help_text='Link to TransferRequest if student ID needs to be updated (e.g., shift/campus change).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfer', to='transfers.transferrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='transfers_g_status_155a61_idx'), models.Index(fields=['student'], name='transfers_g_student_f6d687_idx'), models.Index(fields=['campus'], name='transfers_g_campus__ecbe1e_idx'), models.Index(fields=['from_grade', 'to_grade'], name='transfers_g_from_gr_935f54_idx')],
            },
        ),
    ]
