# Generated by Django 5.2.7 on 2025-11-26 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0002_initial'),
        ('coordinator', '0001_initial'),
        ('students', '0002_student_is_active'),
        ('teachers', '0002_initial'),
        ('transfers', '0004_gradeskiptransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('to_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], help_text='Destination shift on target campus.', max_length=20)),
                ('from_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('to_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('from_section', models.CharField(blank=True, max_length=10, null=True)),
                ('to_section', models.CharField(blank=True, max_length=10, null=True)),
                ('skip_grade', models.BooleanField(default=False, help_text='If true, this transfer includes a grade skip to to_grade.')),
                ('status', models.CharField(choices=[('pending_from_coord', 'Pending From-Campus Coordinator'), ('pending_from_principal', 'Pending From-Campus Principal'), ('pending_to_principal', 'Pending To-Campus Principal'), ('pending_to_coord', 'Pending To-Campus Coordinator'), ('approved', 'Approved / Applied'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending_from_coord', max_length=40)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField(help_text='Effective date requested for this campus transfer.')),
                ('decline_reason', models.TextField(blank=True)),
                ('letter_generated_at', models.DateTimeField(blank=True, null=True)),
                ('letter_new_student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('letter_from_campus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_to_campus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_from_class_label', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_to_class_label', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_from_principal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_to_principal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_to_coordinator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_transfers_from', to='campus.campus')),
                ('from_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_from', to='classes.classroom')),
                ('from_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_from_coord', to='coordinator.coordinator')),
                ('from_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_from', to='classes.grade')),
                ('from_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_from_principal', to=settings.AUTH_USER_MODEL)),
                ('initiated_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_initiated', to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_transfers', to='students.student')),
                ('to_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_transfers_to', to='campus.campus')),
                ('to_classroom', models.ForeignKey(blank=True, help_text='Destination classroom after campus transfer (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_to', to='classes.classroom')),
                ('to_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_to_coord', to='coordinator.coordinator')),
                ('to_grade', models.ForeignKey(blank=True, help_text='Optional destination grade (used when skip_grade is enabled).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_to', to='classes.grade')),
                ('to_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_to_principal', to=settings.AUTH_USER_MODEL)),
                ('transfer_request', models.OneToOneField(blank=True, help_text='Auto-created TransferRequest used to perform the ID update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfer', to='transfers.transferrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='transfers_c_status_5c2e20_idx'), models.Index(fields=['student'], name='transfers_c_student_3549bf_idx'), models.Index(fields=['from_campus', 'to_campus'], name='transfers_c_from_ca_e093be_idx')],
            },
        ),
    ]
